# Generated by Django 2.0.3 on 2018-05-06 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('complete_value', models.CharField(max_length=1)),
                ('created_task', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_task', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Species_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('created_task', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('finish_task', models.DateField(verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Species_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpage.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpage.Species_project'),
        ),
        migrations.AddField(
            model_name='project',
            name='species_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpage.Species_Task'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(through='projectpage.UserProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documents',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpage.Species_project'),
        ),
    ]
