# Generated by Django 2.0.3 on 2018-04-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpage.Species_project')),
            ],
        ),
    ]
