# Generated by Django 2.0.3 on 2018-03-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectpage.Species_project'),
            preserve_default=False,
        ),
    ]
