# Generated by Django 2.0.3 on 2018-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
