# Generated by Django 2.0.3 on 2018-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0002_auto_20180325_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='species_project',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
