# Generated by Django 2.0.3 on 2018-04-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0004_auto_20180401_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tpecies_task',
            new_name='species_task',
        ),
    ]
