# Generated by Django 2.0.3 on 2018-04-02 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0007_species_project_created_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finish_task',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species_project',
            name='finish_task',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
    ]
