# Generated by Django 2.0.3 on 2018-04-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0008_auto_20180402_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='species_project',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
